---
- hosts: all
  become: true
  tasks:
  - name: removing ntp package sit tight
    apt:
     name: ntp 
     state: absent
  - name: removing apache2 package sit tight
    apt:
     name: apache2 
     state: absent
